loadTimeData.data = {
    "B": "B",
    "GB": "GB",
    "KB": "KB",
    "MB": "MB",
    "ad": "Ad",
    "addSiteMenuLabel": "Add site",
    "addTopSiteDialogCancelButtonLabel": "Cancel",
    "addTopSiteDialogNameInputPlaceHolder": "Website title",
    "addTopSiteDialogNameLabel": "Name",
    "addTopSiteDialogSaveButtonLabel": "Save",
    "addTopSiteDialogTitle": "Add site",
    "addTopSiteDialogURLInputPlaceHolder": "Website address",
    "addTopSiteDialogURLLabel": "URL",
    "addWidget": "Add",
    "adsTrackersBlocked": "Trackers & ads blocked",
    "backgroundColor": "#303443ff",
    "backgroundImageTitle": "Background Image",
    "bookmarksPageTitle": "View and Manage Bookmarks",
    "boxDdgButton": "Search with DuckDuckGo",
    "boxTorButton": "Learn more about Tor in Brave",
    "boxTorLabel": "Make Private Windows more private",
    "boxTorLabel2": "This Private Window is more private",
    "boxTorText": "Tor hides your IP address from the sites you visit, by routing your browsing through several Tor servers before it reaches your destination. Tor can slow down browsing and some sites might not work at all.",
    "boxTorText2": "Using Private Windows only changes what Brave does on your device — it doesn't change anyone else's behavior. Tor hides your IP address from the sites you visit and makes it somewhat more difficult, but not impossible, for your ISP or employer to see what sites you are visiting. Open a Private Window with Tor from the menu, or with [[ key ]].",
    "boxTorTitle": "with Tor connectivity",
    "brandedWallpaperOptIn": "Show Sponsored Images",
    "braveBackgroundImageOptionTitle": "Brave backgrounds",
    "braveBackgroundsTitle": "Brave backgrounds",
    "braveNewsActionRefresh": "Load new content",
    "braveNewsAllSourcesHeader": "Sources",
    "braveNewsBackButton": "Back",
    "braveNewsBackToDashboard": "Back to $1Dashboard$2",
    "braveNewsCategoryNameAll": "All sources",
    "braveNewsChannel-Brave": "Brave",
    "braveNewsChannel-Business": "Business",
    "braveNewsChannel-Cars": "Cars",
    "braveNewsChannel-Crypto": "Crypto",
    "braveNewsChannel-Culture": "Culture",
    "braveNewsChannel-Entertainment": "Entertainment",
    "braveNewsChannel-Entertainment News": "Entertainment News",
    "braveNewsChannel-Fashion": "Fashion",
    "braveNewsChannel-Film and TV": "Film and TV",
    "braveNewsChannel-Food": "Food",
    "braveNewsChannel-Fun": "Fun",
    "braveNewsChannel-Gaming": "Gaming",
    "braveNewsChannel-Health": "Health",
    "braveNewsChannel-Home": "Home",
    "braveNewsChannel-Music": "Music",
    "braveNewsChannel-Politics": "Politics",
    "braveNewsChannel-Regional News": "Regional News",
    "braveNewsChannel-Science": "Science",
    "braveNewsChannel-Sports": "Sports",
    "braveNewsChannel-Tech News": "Tech News",
    "braveNewsChannel-Tech Reviews": "Tech Reviews",
    "braveNewsChannel-Technology": "Technology",
    "braveNewsChannel-Top News": "Top News",
    "braveNewsChannel-Top Sources": "Top Sources",
    "braveNewsChannel-Travel": "Travel",
    "braveNewsChannel-US News": "US News",
    "braveNewsChannel-Weather": "Weather",
    "braveNewsChannel-World News": "World News",
    "braveNewsChannelsHeader": "Channels",
    "braveNewsDirectSearchButton": "Get feeds from $1",
    "braveNewsDirectSearchNoResults": "No feeds found at $1",
    "braveNewsDisableSourceCommand": "Disable content from $1",
    "braveNewsErrorActionLabel": "Try again",
    "braveNewsErrorHeading": "Oops…",
    "braveNewsErrorMessage": "Brave News was unable to fetch content.",
    "braveNewsFeedsHeading": "Following",
    "braveNewsFollowButtonFollowing": "Unfollow",
    "braveNewsFollowButtonNotFollowing": "Follow",
    "braveNewsIntroDescription": "Follow your favorite sources, in a single feed. Just open a tab in Brave, scroll down, and… voila!",
    "braveNewsIntroDescriptionTwo": "Brave News is ad-supported with private, anonymized ads. $1Learn more.$2.",
    "braveNewsIntroTitle": "Turn on Brave News, and never miss a story",
    "braveNewsNoContentActionLabel": "Choose content sources",
    "braveNewsNoContentHeading": "No content",
    "braveNewsNoContentMessage": "Brave News has no content to show.",
    "braveNewsOptInActionLabel": "Turn on Brave News",
    "braveNewsOptOutActionLabel": "No thanks",
    "braveNewsPopularTitle": "Popular",
    "braveNewsResetAction": "Reset Brave News sources",
    "braveNewsResetConfirm": "Reset all your Brave News publisher choices to their default?",
    "braveNewsScrollHint": "Scroll for Brave News",
    "braveNewsSearchPlaceholderLabel": "Search for site, topic, or RSS feed",
    "braveNewsSearchQueryTooShort": "Keep typing to search sources",
    "braveNewsSearchResultsDirectResults": "Direct Results",
    "braveNewsSearchResultsLocalResults": "Results",
    "braveNewsSearchResultsNoResults": "There's nothing here :'(",
    "braveNewsSourcesTitle": "Sources",
    "braveNewsStatusFetching": "Fetching…",
    "braveNewsSuggestionsSubtitle": "Some sources you might like. Suggestions are anonymous and matched only on your device.",
    "braveNewsSuggestionsTitle": "Suggestions",
    "braveNewsTitle": "Brave News",
    "braveNewsViewAllButton": "View All",
    "braveRewardsTitle": "Brave Rewards",
    "braveTalkPromptTitle": "You can start a private call in Brave.",
    "braveTalkWidgetAboutData": "About your data",
    "braveTalkWidgetStartButton": "Start call",
    "braveTalkWidgetTitle": "Brave Talk",
    "braveTalkWidgetWelcomeTitle": "Start a private video call with your friends and colleagues.",
    "cards": "Cards",
    "cardsToggleDesc": "By turning off Cards, all cards currently visible will be hidden. However, you may still be notified of new cards.",
    "cardsToggleTitle": "Cards",
    "clockFormat": "Format",
    "clockFormat12": "12-hour clock",
    "clockFormat24": "24-hour clock",
    "clockFormatDefault": "Automatic",
    "clockTitle": "clock",
    "close": "Close",
    "customBackgroundImageOptionTitle": "Use your own",
    "customBackgroundImageOptionUploadLabel": "Upload from device",
    "customize": "Customize",
    "dashboardSettingsTitle": "Customize Dashboard",
    "day": "day",
    "days": "days",
    "done": "Done",
    "editCardsTitle": "Edit Cards",
    "editSiteTileMenuItem": "Edit site",
    "editTopSiteDialogTitle": "Edit site",
    "estimatedBandwidthSaved": "Bandwidth saved",
    "estimatedTimeSaved": "Time saved",
    "featureCustomBackgroundEnabled": true,
    "featureFlagBraveNTPSponsoredImagesWallpaper": true,
    "featureFlagBraveNewsPromptEnabled": true,
    "fontfamily": "'Segoe UI', Tahoma, sans-serif",
    "fontfamilyMd": "'Segoe UI', Tahoma, sans-serif",
    "fontsize": "75%",
    "gradientColorTitle": "Gradients",
    "headerButton": "Learn more.",
    "headerLabel": "This is a",
    "headerText": "Brave doesn’t remember what you do in a Private Window. Sites you visit won't show up in your history, and cookies vanish when you’re done. Private Windows don’t make you completely anonymous online, though.",
    "headerText1": "Brave never remembers what you do in a Private Window. Sites you visit won't show up in your history. Cookies, form data, and site data vanish when you close the window.",
    "headerText2": "Note that your activity could still be visible to your internet service provider, passive network observers, or your employer (if you're using a work machine or network). For more privacy, open a private window with Tor.",
    "headerTitle": "Private Window",
    "headerTorText": "Brave doesn't store browsing activity from Private Windows. With Tor connectivity, it becomes more difficult for sites to see your true IP address and for network observers to see what sites you visit. However, if your personal safety depends on remaining anonymous, use the Tor Browser instead.",
    "headerTorTitle": "Private Window with Tor connectivity",
    "hide": "Hide",
    "hideWidget": "Hide",
    "historyPageTitle": "View your browsing history",
    "hour": "hour",
    "hours": "hours",
    "httpsUpgraded": "HTTPS Upgrades",
    "language": "en",
    "learnMore": "Learn more",
    "loading": "Loading…",
    "minute": "minute",
    "minutes": "minutes",
    "photoBy": "Photo by",
    "preferencesPageTitle": "Edit Preferences",
    "promoted": "Promoted",
    "refreshBackgroundOnNewTab": "Refresh on every new tab",
    "removeTileMenuItem": "Remove",
    "restoreAll": "Restore All",
    "rewardsAboutRewards": "Using Brave Rewards helps support content creators, and lets you earn BAT.",
    "rewardsAdGrantAmount": "$1 Rewards: $2",
    "rewardsAdGrantTitle": "Your $1 Ad Rewards are here!",
    "rewardsBalanceTitle": "Balance",
    "rewardsBraveRewards": "Brave Rewards",
    "rewardsBrowserCannotReceiveAds": "Oops! Your browser cannot receive Brave Private Ads.",
    "rewardsBrowserNeedsUpdateToSeeAds": "Your browser needs to be updated to continue seeing ads.",
    "rewardsClaimRewards": "Claim Rewards",
    "rewardsClaimTokens": "Claim Tokens",
    "rewardsConnectAccount": "Connect account",
    "rewardsConnectAccountNoProviders": "To earn BAT, users must connect a custodial account to Brave Rewards. Unfortunately, there's no custodian available in your region, so earning isn't available. For now, turning on Brave Rewards will automatically support creators.",
    "rewardsConnectAccountText": "$1Ready to start earning?$2 Connect or create an account with one of our partners.",
    "rewardsContinue": "Continue",
    "rewardsEarningInfoText": "This reflects your estimated earnings range for Brave Ads this month.",
    "rewardsEarningsTitle": "Estimated earnings",
    "rewardsEnableBraveAds": "Enable Brave Ads",
    "rewardsGrantDaysRemaining": "You have $1 left to claim",
    "rewardsHowDoesItWork": "How does it work?",
    "rewardsLearnMore": "Learn more",
    "rewardsLogInToSeeBalance": "$1Log in to $2$3 to see your balance",
    "rewardsOptInHeader": "Earn tokens for private ads you see in Brave",
    "rewardsOptInTerms": "By proceeding, you agree to the $1Terms of Service$2 and $3Privacy Policy$4.",
    "rewardsOptInText": "Support content creators and use your tokens to buy gift cards, exchange for other currencies, and more.",
    "rewardsPaymentCheckStatus": "Check status",
    "rewardsPaymentCompleted": "Congrats! Your $1 rewards have arrived!",
    "rewardsPaymentPending": "Your $1 earnings of $2 will arrive in $3.",
    "rewardsPaymentProcessing": "Your $1 earnings of $2 are on the way. Keep an eye out!",
    "rewardsSelectCountryHeader": "Select your country",
    "rewardsSelectCountryText": "To continue using Brave Rewards, select your country so we can show you the right options and ads for your region. $1Privacy Policy$2",
    "rewardsSettings": "Rewards settings",
    "rewardsStartUsingRewards": "Start using Rewards",
    "rewardsTokenGrantTitle": "A token grant is available!",
    "rewardsUnsupportedRegionNoticeHeader": "Sorry, Brave Rewards is not available",
    "rewardsUnsupportedRegionNoticeLearnMore": "$1Learn more$2",
    "rewardsUnsupportedRegionNoticeSubheader": "Unfortunately, it looks like you’re in a region where Brave Rewards is not available.",
    "rewardsUnsupportedRegionNoticeText1": "Don’t worry.",
    "rewardsUnsupportedRegionNoticeText2": "You can still browse privately!",
    "rewardsVBATNoticeText1": "On $1, we will be discontinuing support for existing virtual BAT balances. Connect a custodial account before this date so we can transfer your earned balance to your custodial account, otherwise your balance will be lost.",
    "rewardsVBATNoticeText2": "On $1, we will be discontinuing support for existing virtual BAT balances. Unfortunately, there are no available custodians in your region ($2) to withdraw your earnings. Until then, you can still contribute to your favorite creators.",
    "rewardsVBATNoticeTitle1": "Action required: Connect a custodial account or your vBAT will be lost",
    "rewardsVBATNoticeTitle2": "You still have time to contribute your vBAT to your favorite creators",
    "rewardsWidgetBraveRewards": "Brave Rewards",
    "rewardsWidgetDesc": "Earn tokens for watching privacy-respecting ads.",
    "searchPromotionNTPPopupBottom": "Try Brave Search now",
    "searchPromotionNTPPopupDesc": "Brave Search doesn't bias or censor results, and it doesn't track you, your queries, or your clicks.",
    "searchPromotionNTPPopupTitle1": "Want even better privacy?",
    "searchPromotionNTPPopupTitle2": "It's time to ditch Google.",
    "searchPromotionSearchBoxPlaceholderLabel": "Search the web privately",
    "second": "second",
    "seconds": "seconds",
    "settingsNavigateBack": "Back",
    "showBackgroundImage": "Show Background Images",
    "showBraveStats": "Show Brave Stats",
    "showClock": "Show Clock",
    "showFavoritesDesc": "Top sites are curated by you",
    "showFavoritesLabel": "Favorites",
    "showFavoritesMenuLabel": "Show favorites",
    "showFrecencyDesc": "Top sites are suggested based on websites you visit often",
    "showFrecencyLabel": "Frequently Visited",
    "showFrecencyMenuLabel": "Show frequently visited",
    "showRewards": "Show Brave Rewards",
    "showTopSites": "Top Sites",
    "solidColorTitle": "Solid colors",
    "sponsoredImageEarningTitle": "You're earning BAT for Sponsored Images.",
    "sponsoredImageEnableRewards": "Enable Rewards",
    "sponsoredImageNotEarningTitle": "You can earn for seeing Sponsored Images.",
    "sponsoredImageOffRewardsOnDescription": "As a Brave Rewards user, you can earn BAT for seeing Sponsored Images.",
    "sponsoredImageOnAdsOff": "You can earn BAT for seeing Sponsored Images when you enable Brave Ads. When Brave Ads is off, turning on Sponsored Images still supports Brave's mission.",
    "sponsoredImageOnDescription": "As a Brave Rewards user, you earn BAT for Sponsored Images you see. Disabling Sponsored Images will reduce how much you earn.",
    "sponsoredImageOnRewardsOnNoCustodianDescription": "You can earn BAT for seeing Sponsored Images when you connect a custodial account to Brave Rewards. In the meantime, you're helping to support creators with Sponsored Images.",
    "sponsoredImageRewardsOffDescription": "You can earn BAT for seeing Sponsored Images with Brave Rewards. Not a Rewards user? Turning on Sponsored Images still supports Brave's mission.",
    "statsTitle": "Brave Stats",
    "textdirection": "ltr",
    "thumbRemoved": "Top site removed.",
    "topSitesTitle": "top sites",
    "undoRemoved": "Undo"
};
